---
title: "Existential Crisis"
date: 2018-04-26
---
title: If Mike is short for Michael then bike is short for Bikael
author: James Ritesr
email: mr.yang6969@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Help please
▓▓▓▓ 
▒▒▒▓▓ 
▒▒▒▒▒▓ 
▒▒▒▒▒▒▓ 
▒▒▒▒▒▒▓ 
▒▒▒▒▒▒▒▓ 
▒▒▒▒▒▒▒▓▓▓ 
▒▓▓▓▓▓▓░░░▓ 
▒▓░░░░▓░░░░▓ 
▓░░░░░░▓░▓░▓ 
▓░░░░░░▓░░░▓ 
▓░░▓░░░▓▓▓▓ 
▒▓░░░░▓▒▒▒▒▓ 
▒▒▓▓▓▓▒▒▒▒▒▓ 
▒▒▒▒▒▒▒▒▓▓▓▓ 
▒▒▒▒▒▓▓▓▒▒▒▒▓ 
▒▒▒▒▓▒▒▒▒▒▒▒▒▓ 
▒▒▒▓▒▒▒▒▒▒▒▒▒▓ 
▒▒▓▒▒▒▒▒▒▒▒▒▒▒▓ 
▒▓▒▓▒▒▒▒▒▒▒▒▒▓ 
▒▓▒▓▓▓▓▓▓▓▓▓▓ 
▒▓▒▒▒▒▒▒▒▓ 
▒▒▓▒▒▒▒▒▓ 
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
